version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nf-system-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wai_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nf_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: